name: Gitea CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'
  PYTHON_VERSION: '3.12'

jobs:
  security-scans:
    name: Security Scans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Python venv and add to PATH
        run: |
          python3 -m venv .ci-venv
          echo "$PWD/.ci-venv/bin" >> $GITHUB_PATH

      - name: Install security tools
        run: |
          pip install bandit checkov pip-audit truffleHog

      - name: Install trufflehog Go binary
        run: |
          mkdir -p "$HOME/.local/bin"
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh \
            | sh -s -- -b "$HOME/.local/bin"
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Create security reports directory
        run: mkdir -p security-reports

      - name: Run Bandit SAST
        run: |
          bandit -r src/ infrastructure/ scripts/ \
            -f json -o security-reports/bandit-report.json \
            --severity-level medium --confidence-level medium || true
        continue-on-error: true

      - name: Run Checkov Infrastructure Scan
        run: |
          checkov -d infrastructure/ \
            --output json --output-file-path security-reports || true
        continue-on-error: true

      - name: Run TruffleHog Secrets Scan
        run: |
          trufflehog filesystem . \
            --json --no-update > security-reports/trufflehog-report.json || true
        continue-on-error: true

      - name: Run pip-audit Dependency Scan
        run: |
          pip-audit --format json \
            --output security-reports/pip-audit-report.json \
            --desc --progress-spinner off || true
        continue-on-error: true

      - name: Show Security Reports
        run: |
          echo "=== Bandit SAST Report ==="
          head -50 security-reports/bandit-report.json || echo "No Bandit report"
          echo ""
          echo "=== Checkov Infrastructure Scan ==="
          head -50 security-reports/results_json.json || echo "No Checkov report"
          echo ""
          echo "=== TruffleHog Secrets Scan ==="
          head -50 security-reports/trufflehog-report.json || echo "No TruffleHog report"
          echo ""
          echo "=== pip-audit Dependency Scan ==="
          head -50 security-reports/pip-audit-report.json || echo "No pip-audit report"
        continue-on-error: true

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify PostgreSQL and test database
        # Prerequisite: run once as a privileged user:
        #   sudo -u postgres psql -f scripts/sql/setup-ci-testdb.sql
        run: |
          pg_isready -h localhost -p 5432 || {
            echo "ERROR: PostgreSQL is not accepting connections on localhost:5432"
            exit 1
          }
          psql "postgresql://testuser:testpassword@localhost:5432/tutor_system_test" \
            -c '\conninfo' || {
            echo ""
            echo "ERROR: Cannot connect to tutor_system_test as testuser."
            echo "Run the one-time setup (with your sudo password):"
            echo "  sudo -u postgres psql -f scripts/sql/setup-ci-testdb.sql"
            exit 1
          }

      - name: Create Python venv and add to PATH
        run: |
          python3 -m venv .ci-venv
          echo "$PWD/.ci-venv/bin" >> $GITHUB_PATH

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov pytest-xdist

      - name: Run database migrations
        run: |
          export DATABASE_URL="postgresql://testuser:testpassword@localhost:5432/tutor_system_test"
          psql "$DATABASE_URL" -f src/lambda_functions/migration_runner/migrations/schema_v2.sql

      - name: Run backend tests
        run: |
          export DATABASE_URL="postgresql://testuser:testpassword@localhost:5432/tutor_system_test"
          export PYTHONPATH="${PYTHONPATH}:$(pwd)/src"
          pytest tests/ -v --cov=src --cov-report=term-missing \
            --ignore=tests/integration \
            --ignore=tests/test_localstack_integration.py \
            --ignore=tests/test_kms_secrets.py \
            --ignore=tests/test_domain_unit.py \
            --ignore=tests/test_quiz_unit.py \
            --ignore=tests/test_auth_properties.py \
            --ignore=tests/test_auth_security.py \
            --ignore=tests/test_security_controls.py \
            --ignore=tests/test_progress_properties.py \
            --ignore=tests/test_database_schema_properties.py \
            --ignore=tests/test_deployment_validation.py \
            --ignore=tests/test_model_utils_unit.py \
            --ignore=tests/test_batch_upload_unit.py \
            --ignore=tests/test_cognito_auth_properties.py \
            --ignore=tests/test_cognito_integration.py \
            --ignore=tests/test_domain_properties.py \
            --ignore=tests/test_progress_unit.py \
            --ignore=tests/property_tests/test_quiz_properties.py \
            --ignore=tests/test_quiz_properties.py \
            --ignore=tests/test_config_unit.py \
            --ignore=tests/test_security_middleware_unit.py \
            --ignore=tests/test_security_monitoring.py \
            --ignore=tests/test_auth_unit.py \
            --ignore=tests/test_batch_upload_properties.py \
            -m "not integration"

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify Node.js
        run: |
          node --version
          npm --version

      - name: Build frontend
        env:
          VITE_API_BASE_URL: https://3kuv3v3u89.execute-api.us-east-1.amazonaws.com/prod
          VITE_COGNITO_USER_POOL_ID: us-east-1_Bg1FA4097
          VITE_COGNITO_USER_POOL_CLIENT_ID: 6d56bp4dfiu42chkdjjmln6bb9
          VITE_AWS_REGION: us-east-1
        run: |
          cd frontend
          npm ci
          npm run build

  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: [test-backend, build-frontend]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build frontend for CDK asset
        env:
          VITE_API_BASE_URL: https://3kuv3v3u89.execute-api.us-east-1.amazonaws.com/prod
          VITE_COGNITO_USER_POOL_ID: us-east-1_Bg1FA4097
          VITE_COGNITO_USER_POOL_CLIENT_ID: 6d56bp4dfiu42chkdjjmln6bb9
          VITE_AWS_REGION: us-east-1
        run: |
          cd frontend
          npm ci
          npm run build

      - name: Verify AWS secrets are configured
        # If this step fails, add secrets at:
        # http://192.168.1.103:3000/jumbob/ai-tutor-system/settings/secrets
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          if [ -z "$AWS_ACCESS_KEY_ID" ] || [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
            echo "ERROR: AWS_ACCESS_KEY_ID and/or AWS_SECRET_ACCESS_KEY are not set."
            echo "Add them at: http://192.168.1.103:3000/jumbob/ai-tutor-system/settings/secrets"
            exit 1
          fi
          echo "AWS credentials are present."

      - name: Verify CDK is available
        run: /usr/local/bin/cdk --version

      - name: Create Python venv and add to PATH
        run: |
          python3 -m venv .ci-venv
          echo "$PWD/.ci-venv/bin" >> $GITHUB_PATH

      - name: Install CDK Python dependencies
        run: |
          cd infrastructure
          pip install -r requirements.txt

      - name: CDK synth dry-run
        run: |
          cd infrastructure
          cdk synth --app "python3 app_multistack.py" --all
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Deploy all stacks
        run: |
          cd infrastructure
          cdk deploy --app "python3 app_multistack.py" --all --require-approval never
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Run database migrations
        run: |
          aws lambda invoke --function-name BackendStack-dev-MigrationRunnerFunction2F9B9A8B-4WhuBkExC6sf /tmp/migration-output.json
          cat /tmp/migration-output.json
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

      - name: Prune old ECR images
        run: |
          for repo in answer-evaluator answer-evaluator-inference cdk-hnb659fds-container-assets-257949588978-us-east-1; do
            aws ecr put-lifecycle-policy --repository-name $repo \
              --lifecycle-policy-text '{"rules":[{"rulePriority":1,"selection":{"tagStatus":"any","countType":"imageCountMoreThan","countNumber":2},"action":{"type":"expire"}}]}'
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1

  notify:
    name: Notify Results
    runs-on: ubuntu-latest
    needs: [security-scans, test-backend, build-frontend, deploy]
    if: always()
    steps:
      - name: Check results
        run: |
          echo "Security Scans: ${{ needs.security-scans.result }}"
          echo "Backend Tests:  ${{ needs.test-backend.result }}"
          echo "Frontend Build: ${{ needs.build-frontend.result }}"
          echo "Deploy:         ${{ needs.deploy.result }}"
